name: Release & Version

on:
  push:
    branches: [ main ]

permissions:
  contents: write     # create releases & upload assets
  id-token: write     # REQUIRED for SLSA provenance (OIDC)

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # ---------------------------
      # SBOM GENERATION (CycloneDX)
      # ---------------------------
      - name: Generate SBOM
        run: |
          npm install -g @cyclonedx/cyclonedx-npm
          cyclonedx-npm --output-file sbom.xml

      # ---------------------------
      # ARTIFACT INTEGRITY
      # ---------------------------
      - name: Generate checksum
        run: sha256sum sbom.xml > sbom.sha256

      # ---------------------------
      # SLSA BUILD PROVENANCE
      # ---------------------------

      - name: Generate provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1
        with:
          artifact_path: sbom.xml


      # ---------------------------
      # RELEASE
      # ---------------------------
      - name: Install semantic-release
        run: npm install -g semantic-release \
          @semantic-release/changelog \
          @semantic-release/git \
          @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
